name: Kontrollera produktstatus

on:
  schedule:
    - cron: '*/5 * * * *'  # Kör var 5:e minut
  workflow_dispatch:        # Möjlighet att köra manuellt

jobs:
  check_status:
    runs-on: ubuntu-latest

    steps:
    - name: Klona repot
      uses: actions/checkout@v3

    - name: Installera Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache Python-paket
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache Playwright-browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Cache status-hashes
      uses: actions/cache@v4
      with:
        path: status_hashes.json
        key: status-hashes-${{ hashFiles('status_hashes.json') }}
        restore-keys: |
          status-hashes-

    - name: Installera beroenden
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install --with-deps

    - name: Kör bevakningsskriptet
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: python web-monitor.py
