name: Kontrollera produktstatus

on:
  schedule:
    - cron: '*/5 * * * *'  # Kör var 5:e minut
  workflow_dispatch:      # Gör det möjligt att köra manuellt

jobs:
  check_status:
    runs-on: ubuntu-latest

    steps:
    - name: Klona repot
      uses: actions/checkout@v3

    - name: Installera Python + Playwright
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install --with-deps

    - name: Kör bevakningsskriptet
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: python web-monitor.py
